###
GET  http://localhost:3333/produtos  
Content-Type: application/json

###
GET  http://localhost:3333/produtos/1?size=GG&minPrice=300&maxPrice=350&color=azul
Content-Type: application/json

###
GET  http://localhost:3333/departamentos
Content-Type: application/json
###
GET  http://localhost:3333/clientes
Content-Type: application/json
###
GET  http://localhost:3333/enderecos
Content-Type: application/json
###
GET  http://localhost:3333/admin
Content-Type: application/json
###
GET  http://localhost:3333/logins
Content-Type: application/json
###
GET  http://localhost:3333/pedidos
Content-Type: application/json
###
GET  http://localhost:3333/produtosEstoque
Content-Type: application/json

###
GET  http://localhost:3333/itensCarrinho/usuario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0ZXNlc0BnbWFpbC5jb20iLCJpYXQiOjE3MTg4MDY2Mjl9.ZZHKcX0S_Rm_KuLzOm7hoFVlmr7RQzGJSoj17TnCrjY
Content-Type: application/json
###
GET  http://localhost:3333/endereco/usuario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0ZXNlc0BnbWFpbC5jb20iLCJpYXQiOjE3MTg4MDY2Mjl9.ZZHKcX0S_Rm_KuLzOm7hoFVlmr7RQzGJSoj17TnCrjY
Content-Type: application/json
###
GET  http://localhost:3333/pedidos/usuario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0ZXNlc0BnbWFpbC5jb20iLCJpYXQiOjE3MTg4MDY2Mjl9.ZZHKcX0S_Rm_KuLzOm7hoFVlmr7RQzGJSoj17TnCrjY
Content-Type: application/json

###
GET  http://localhost:3333/produto/1/estoque
Content-Type: application/json